apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: order-service
  name: order-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - image: sayy2bipin/order-service:02-assign3-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: order-service
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service
  name: order-service
  namespace: default
spec:
  ports:
  - port: 8686
    targetPort: 8686
  selector:
    app: order-service
  sessionAffinity: None
  type: ClusterIP
