apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - image: sayy2bipin/user-service:01-assign3-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: user-service
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: default
spec:
  ports:
  - port: 8700
    targetPort: 8700
  selector:
    app: user-service
  sessionAffinity: None
  type: ClusterIP
