apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: aggregation-service
  name: aggregation-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aggregation-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aggregation-service
    spec:
      containers:
      - image: sayy2bipin/aggregation-service:01-assign3-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: aggregation-service
        env:
          - name: USER_SERVICE_URI
            value: http://user-service
          - name: ORDER_SERVICE_URI
            value: http://order-service
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aggregation-service
  name: aggregation-service
  namespace: default
spec:
  ports:
  - nodePort: 30151
    port: 8800
    protocol: TCP
    targetPort: 8800
  selector:
    app: aggregation-service
  sessionAffinity: None
  type: LoadBalancer
